version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql-ediaristas
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php-my-admin-ediarista
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
