global:
  scrape_interval: 15s
  scrape_timeout: 15s

  external_labels:
    monitor: "dev-monitor"

scrape_configs:
  - job_name: 'Spring Boot Application input'
    scheme: http
    static_configs:
      - targets: [ 'app:8000', 'load-balancer:8080' ]
        labels:
          application: 'My Spring Boot Application'
    basic_auth:
      username: user
      password: password